/**
 * Init command - Interactive setup wizard
 * 
 * Usage: cm init
 */
import { Command } from 'commander';
import { writeFile } from 'fs/promises';
import { join } from 'path';
import inquirer from 'inquirer';
import chalk from 'chalk';

interface SetupAnswers {
  llmProvider: string;
  llmModel: string;
  archetype: string;
  orientation: string;
  voice: string;
}

export const initCommand = new Command('init')
  .description('Interactive setup wizard')
  .option('-y, --yes', 'Use defaults without prompting', false)
  .action(async (options) => {
    console.log(chalk.bold('\n🎬 content-machine setup\n'));
    
    let config: Record<string, unknown>;
    
    if (options.yes) {
      // Use defaults
      config = getDefaultConfig();
    } else {
      // Interactive prompts - use sequential prompts for type safety
      const { llmProvider } = await inquirer.prompt<{ llmProvider: string }>({
        type: 'list',
        name: 'llmProvider',
        message: 'Which LLM provider would you like to use?',
        choices: ['openai', 'anthropic'],
        default: 'openai',
      });

      const { llmModel } = await inquirer.prompt<{ llmModel: string }>({
        type: 'input',
        name: 'llmModel',
        message: 'Which model would you like to use?',
        default: llmProvider === 'openai' ? 'gpt-4o' : 'claude-3-5-sonnet-20241022',
      });

      const { archetype } = await inquirer.prompt<{ archetype: string }>({
        type: 'list',
        name: 'archetype',
        message: 'Default content archetype?',
        choices: ['listicle', 'versus', 'howto', 'myth', 'story', 'hot-take'],
        default: 'listicle',
      });

      const { orientation } = await inquirer.prompt<{ orientation: string }>({
        type: 'list',
        name: 'orientation',
        message: 'Default video orientation?',
        choices: ['portrait', 'landscape', 'square'],
        default: 'portrait',
      });

      const { voice } = await inquirer.prompt<{ voice: string }>({
        type: 'input',
        name: 'voice',
        message: 'Default TTS voice?',
        default: 'af_heart',
      });
      
      config = {
        defaults: {
          archetype,
          orientation,
          voice,
        },
        llm: {
          provider: llmProvider,
          model: llmModel,
          temperature: 0.7,
        },
        audio: {
          tts_engine: 'kokoro',
          asr_engine: 'whisper',
        },
        visuals: {
          provider: 'pexels',
          fallback_provider: 'pixabay',
        },
        render: {
          fps: 30,
          codec: 'h264',
        },
      };
    }
    
    // Write config file
    const configPath = join(process.cwd(), '.content-machine.toml');
    const tomlContent = generateToml(config);
    
    await writeFile(configPath, tomlContent, 'utf-8');
    
    console.log(chalk.green('\n✅ Configuration saved to .content-machine.toml\n'));
    
    // Show environment variable hints
    console.log(chalk.yellow('📝 Don\'t forget to set your API keys:\n'));
    console.log(chalk.gray('   export OPENAI_API_KEY=sk-...'));
    console.log(chalk.gray('   export PEXELS_API_KEY=...'));
    console.log(chalk.gray('   # Or add them to a .env file\n'));
    
    console.log(chalk.blue('🚀 Ready! Run: cm generate "Your topic here"\n'));
  });

function getDefaultConfig(): Record<string, unknown> {
  return {
    defaults: {
      archetype: 'listicle',
      orientation: 'portrait',
      voice: 'af_heart',
    },
    llm: {
      provider: 'openai',
      model: 'gpt-4o',
      temperature: 0.7,
    },
    audio: {
      tts_engine: 'kokoro',
      asr_engine: 'whisper',
    },
    visuals: {
      provider: 'pexels',
    },
    render: {
      fps: 30,
      codec: 'h264',
    },
  };
}

function generateToml(config: Record<string, unknown>): string {
  const lines: string[] = [
    '# content-machine configuration',
    '# Generated by cm init',
    '',
  ];
  
  for (const [section, values] of Object.entries(config)) {
    lines.push(`[${section}]`);
    for (const [key, value] of Object.entries(values as Record<string, unknown>)) {
      if (typeof value === 'string') {
        lines.push(`${key} = "${value}"`);
      } else if (typeof value === 'number') {
        lines.push(`${key} = ${value}`);
      } else if (typeof value === 'boolean') {
        lines.push(`${key} = ${value}`);
      }
    }
    lines.push('');
  }
  
  return lines.join('\n');
}
